eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/
# 抓取服务列表
    registry-fetch-interval-seconds: 30
#    fetch-registry: true  #缓存更新属性
#    registry-fetch-interval-seconds: 30

  instance:
    #心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 30
    #告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 60

server:
  port: 8100
#  servlet:
#    context-path: /isport/concumer_basic
spring:
  application:
    name: concumer-basic

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

http:
  url: localhost
  
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
        
foo: new ok ok ok concumer

